CREATE TABLE PERSON (
	
	ID INT IDENTITY(10000,1) PRIMARY KEY NOT NULL,
	PERSONID INT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	GENDER VARCHAR(10) NOT NULL,
	DOB DATE,
	ADDRESS VARCHAR(500) NULL,
	EMAIL VARCHAR(50) NOT NULL,
	MOBILE VARCHAR(50) NOT NULL,
	QUALIFICATION NVARCHAR(MAX) NULL,
	EXPERIANCE NVARCHAR(MAX) NULL,
	INTEREST NVARCHAR(500) NULL,

);

ALTER TABLE PERSON ADD IMGPATH VARCHAR(200);