CREATE PROC [dbo].[USP_PERSON_CANDIDATEINSERTUPDATE]
(
	@INT_PERSONID INT,
	@STR_NAME VARCHAR(100),
	@STR_GENDER VARCHAR(10),
	@DT_DOB DATETIME,
	@STR_ADDRESS VARCHAR(500),
	@STR_EMAIL VARCHAR(50),
	@STR_MOBILE VARCHAR(50),
	@STR_QUALIFICATION NVARCHAR(MAX),
	@STR_EXPERIANCE NVARCHAR(MAX),
	@STR_INTEREST NVARCHAR(500),
	@INT_DBOPERATION INT

)
AS
BEGIN
BEGIN TRY

DECLARE @STR_MESSAGE VARCHAR(200);
DECLARE @INT_SUCCESS INT = 0;

IF @INT_DBOPERATION = 0 
BEGIN

	INSERT INTO PERSON (PERSONID,NAME,GENDER,DOB,ADDRESS,EMAIL,MOBILE,QUALIFICATION,EXPERIANCE,INTEREST) VALUES (@INT_PERSONID,@STR_NAME,@STR_GENDER,@DT_DOB,@STR_ADDRESS,@STR_EMAIL,@STR_MOBILE,@STR_QUALIFICATION,@STR_EXPERIANCE,@STR_INTEREST)

	SET @STR_MESSAGE = 'Insert Success';
	SET @INT_SUCCESS = 1;

	END
	ELSE
	BEGIN

		UPDATE PERSON SET NAME=@STR_NAME WHERE PERSONID='00000'

		SET @STR_MESSAGE = 'Update Success';
	SET @INT_SUCCESS = 1;

	END


	SELECT @STR_MESSAGE AS Message,
	@INT_SUCCESS AS Success 

	END TRY
	BEGIN CATCH
	   DECLARE @ErrorMessage NVARCHAR(4000) ;
            DECLARE @ErrorSeverity INT ;
            DECLARE @ErrorState INT ;

            SELECT  @ErrorMessage = ERROR_MESSAGE() ,
                    @ErrorSeverity = ERROR_SEVERITY() ,
                    @ErrorState = ERROR_STATE()

            RAISERROR(@ErrorMessage,@ErrorSeverity,@ErrorState) ;
	
       END CATCH
END