

CREATE PROC [dbo].[USP_JOB_INSERTJOBDETAILS]

(

	@STR_JOBTITLE NVARCHAR(100),

	@STR_JOBDESC NVARCHAR(MAX),

	@DT_JOBPOSTEDDATE DATETIME,

	@STR_QUALIFICATION NVARCHAR(300),

	@STR_APPLYLINK VARCHAR(500)

)

AS

	BEGIN

		BEGIN TRY

			DECLARE @BIT_SUCCESS INT = 0;

			DECLARE @JOBNUMBER INT;

					INSERT INTO JOB(JOBTITLE,JOBDESC,POSTEDDATE,QUALIFICATION,APPLYLINK) VALUES (@STR_JOBTITLE,@STR_JOBDESC,@DT_JOBPOSTEDDATE,@STR_QUALIFICATION,@STR_APPLYLINK)

					SET @BIT_SUCCESS = 1;

					SET @JOBNUMBER= SCOPE_IDENTITY();

			SELECT @JOBNUMBER AS JOB_NUMBER, @BIT_SUCCESS AS SUCCESS 


		END TRY
		

		BEGIN CATCH

			DECLARE @ErrorMessage NVARCHAR(4000) ;

            DECLARE @ErrorSeverity INT ;

            DECLARE @ErrorState INT ;



            SELECT  @ErrorMessage = ERROR_MESSAGE() ,

                    @ErrorSeverity = ERROR_SEVERITY() ,

                    @ErrorState = ERROR_STATE()



            RAISERROR(@ErrorMessage,@ErrorSeverity,@ErrorState) ;


       END CATCH

	END
