ALTER PROC [dbo].[usp_FetchDiscussion]
 
 @JOBNO INT

AS
 BEGIN

			SET NOCOUNT ON

			--SELECT ID, CHATID,USERNAME,JOBNO,MESSAGES,MSGDATETIME FROM DISCUSSION WHERE JOBNO=@JOBNO ORDER BY MSGDATETIME ASC
			SELECT DISCUSSION.ID, CHATID,DISCUSSION.USERNAME,JOBNO,MESSAGES,MSGDATETIME,users.PERSONID,ISNULL(NAME,'anonymous') DisplayName,IMGPATH FROM DISCUSSION left join Users on Discussion.USERNAME=Users.USERNAME  left join person on Person.PERSONID=Users.PERSONID WHERE JOBNO=@JOBNO ORDER BY MSGDATETIME ASC

 END
GO